research_vivo_task:
  description: >
    This task aims to gather updated information about the services offered by Vivo in 2024, based on the user's input: {input}". The research will cover aspects such as mobile phone plans, fixed internet, TV packages, data offers, and other relevant services provided by the company.
  expected_output: >
    A detailed and accurate summary of Vivo's current services in 2024, including information on plans, promotional offers, pricing, package features, and any other relevant services, tailored to the specific inquiry or question presented by the user.
  agent: research_vivo_agent

cancellation_vivo_task:
  description: >
    This task involves understanding which Vivo service the user wants to cancel, based on this input: '{input}', and gathering all the necessary data required for the cancellation process. The task includes identifying the service in question, collecting account details, understanding the reasons for cancellation, and informing the user about any applicable fees or conditions related to the termination of the service. The agent will guide the user through a set of questions to ensure that all essential information is obtained.
  expected_output: >
    A complete collection of data required for canceling the chosen Vivo service. This includes:
    - The type of service the user wants to cancel (mobile, internet, TV, etc.).
    - The user’s account details (account number, name, and contact information).
    - The reason for cancellation provided by the user.
    - Any details regarding the service's terms, such as minimum contract period, cancellation fees, or penalties.
    - Clear instructions for the next steps in the cancellation process.
  agent: cancellation_vivo_agent