classification_task:
  description: >
    Classify the customer's request into categories such as 'information', 'contracting', 'problems', or 'cancellation'.
  expected_output: >
    ["information", "contracting", "problems", 'cancellation']
  agent: classification_agent