classification_task:
  description: >
    Classify the customer's request into categories such as 'internet', 'second_copy', 'plans', or 'other'.
  expected_output: >
    ["internet", "second_copy", "plans", "other"]
  agent: classification_agent