research_vivo_task:
  description: >
    This task aims to gather updated information about the services offered by Vivo in 2024, based on the user's input: {input}". The research will cover aspects such as mobile phone plans, fixed internet, TV packages, data offers, and other relevant services provided by the company.
  expected_output: >
    A detailed and accurate summary of Vivo's current services in 2024, including information on plans, promotional offers, pricing, package features, and any other relevant services, tailored to the specific inquiry or question presented by the user.
  agent: research_vivo_agent